### ISSUE TITLE
Can't build on OSX Catalina

### ISSUE THREAD

**Issue by Ku6ep** [golded-plus/golded-plus#22]
Got this error: 
`/usr/local/include/regex.h:22:10: fatal error: 'boost/cregex.hpp' file not found`

**Comment by dukelsky** [comment]
Doesn't 
https://github.com/golded-plus/golded-plus/releases/download/golded-plus-1.1.5-20180707-1/golded-plus-1.1.5-20180707-Darwin.x86_64.tar.gz
work for you? And no, 'boost' is not mentioned in the sources.

**Comment by Ku6ep** [comment]
No, I try it, but it's not run under Catalina.

**Comment by dukelsky** [comment]
Please try to build the project using Cmake:
Run CMake to configure the build tree
$ cmake -H. -Bbuild -DBUILD_SHARED_LIBS=OFF
Afterwards, generated files can be used to compile the project.
 $ cmake --build build
Make distribution tgz (optional)
$ cpack -G TGZ --config build/CPackConfig.cmake
Install the built files (optional).
 $ cmake --build build --target install

**Comment by Ku6ep** [comment]
> cmake --build build
5 warnings generated.
[ 98%] Building CXX object golded3/CMakeFiles/golded.dir/golded3.cpp.o
/../../golded-plus-master/golded3/golded3.cpp:190:10: fatal error: 'mygolded.h' file not found
#include <mygolded.h>
         ^~~~~~~~~~~~

**Comment by dukelsky** [comment]
So, you are going to compile sources but have not read docs/building.txt :-(

**Comment by dukelsky** [comment]
So, you are going to compile sources but you have not read docs/building.txt :-(
