### ISSUE TITLE
Synchronet Config Change

### ISSUE THREAD

**Issue by DaiTengu** [golded-plus/golded-plus#77]
Synchronet 3.20 migrated configuration files from binary files to text-based .ini files.   

Any new areas added to Synchronet won't get picked up by Golded+, since msgs.cnf is no longer written to.   New installs won't have a msgs.cnf, so no areas will be found.

https://wiki.synchro.net/history:newcfgfiles

An example of the `msgs.ini` format from gitlab.synchro.net:

https://gitlab.synchro.net/main/sbbs/-/blob/master/ctrl/msgs.ini

**Comment by vitaliy-aksyonov** [comment]
@DaiTengu Could you try if my changes work for you?

**Comment by DaiTengu** [comment]
Sorry I never got back to you on this. life got in the way!  It seems to work quite well,  thanks!
